name: Build Windows packaged binary

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm install --ignore-scripts
          npm install @homebridge/node-pty-prebuilt-multiarch

      - name: Build and Package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run prebuild-windows
          npm run build-windows

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Installer
          path: dist/*.exe
          if-no-files-found: error
